// File generated by Antigravity manually from google-services.json and GoogleService-Info.plist.
// This is used to initialize Firebase without relying on native resource generation.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Flutter apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await dotenv.load(fileName: ".env");
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: dotenv.get('FIREBASE_ANDROID_API_KEY'),
        appId: '1:963254573064:android:636ad93837ed6113ffd9bd',
        messagingSenderId: '963254573064',
        projectId: 'todo-app26-ba985',
        storageBucket: 'todo-app26-ba985.firebasestorage.app',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: dotenv.get('FIREBASE_IOS_API_KEY'),
        appId: '1:963254573064:ios:7fc4ab22dc9e1150ffd9bd',
        messagingSenderId: '963254573064',
        projectId: 'todo-app26-ba985',
        storageBucket: 'todo-app26-ba985.firebasestorage.app',
        iosBundleId: 'com.herody.todoapp26',
      );
}
